<?php

namespace User;

use App\User\Application\UserGetUseCase;
use App\User\Infrastructure\Models\User;
use App\User\Infrastructure\Repositories\UserEloquentRepository;
use Tests\TestCase;

class UserGetUseCaseTest extends TestCase
{
    protected UserGetUseCase $userGetUseCase;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->userGetUseCase = new UserGetUseCase(new UserEloquentRepository());
    }

    public function test_get_all_users(): void
    {
        User::factory(5)->create();

        $data = $this->userGetUseCase->getAllUsers();
        $this->assertCount(5, $data);
    }

    public function test_get_by_id(): void
    {
        $user = User::factory()->create();
        $userOutput = $this->userGetUseCase->getUserById($user->id);

        $this->assertEquals($user->name, $userOutput->name);
        $this->assertEquals($user->email, $userOutput->email);
    }

    public function test_get_by_email(): void
    {
        $user = User::factory()->create();
        $userOutput = $this->userGetUseCase->getUserByEmail($user->email);

        $this->assertEquals($user->name, $userOutput->name);
        $this->assertEquals($user->email, $userOutput->email);
    }
}
