version: '3'

services:
  web:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: test-backend
    volumes:
      - .:/var/www/html
      - ./default:/etc/nginx/sites-available/default
    ports:
      - "8000:80"
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: test-mysql
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./docker/data:/var/lib/mysql
    ports:
      - 3310:3306
